# Generated by Django 4.1.3 on 2023-01-03 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_commentmodel_time_commentmodel_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subscribers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(default=None, max_length=254, unique=True)),
            ],
        ),
        migrations.AlterField(
            model_name='commentmodel',
            name='time',
            field=models.CharField(default='Tue Jan  3 16:00:37 2023', max_length=100),
        ),
    ]
