# Generated by Django 4.1.3 on 2023-01-06 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_subscribers_reason_alter_commentmodel_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commentmodel',
            name='time',
            field=models.CharField(default='Fri Jan  6 12:52:57 2023', max_length=100),
        ),
    ]
