# Generated by Django 4.1.3 on 2023-01-09 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_alter_commentmodel_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commentmodel',
            name='time',
            field=models.CharField(default='Mon Jan  9 14:56:38 2023', max_length=100),
        ),
    ]
