# Generated by Django 4.1.3 on 2023-01-14 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0016_alter_commentmodel_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commentmodel',
            name='time',
            field=models.CharField(default='Sat Jan 14 16:13:31 2023', max_length=100),
        ),
    ]
